<a href="https://colab.research.google.com/github/russellw999/PyTorch-Tutorial-YouTube-Codemy/blob/master/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# TENSOR MATH OPERATIONS

In [3]:
import numpy as np
import torch

In [7]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [8]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [11]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [16]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [17]:
# Mul long hand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [10]:
# Power
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [24]:
# Power longhand
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [25]:
torch.pow(tensor_a, 2)

tensor([ 1,  4,  9, 16])

In [12]:
tensor_a ** -tensor_b

tensor([1, 0, 0, 0])

In [13]:
# Subtract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [15]:
# Sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [18]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [19]:
# Div longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [20]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [22]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [26]:
# Re assignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [27]:
 # tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [28]:
tensor_a

tensor([ 6,  8, 10, 12])

In [29]:
torch.add(tensor_a, tensor_b)

tensor([11, 14, 17, 20])